### ISSUE TITLE
Sharing support

### ISSUE THREAD

**Issue by danirod** [danirod/rectball#42]
### Abstract
Sharing support is finally expected to arrive on Beta 4. With sharing, users can share screenshots and scores of the games that they play. This can be used to show to friends or other people how well they play Rectball.

**Objective**: Let users share their scores using a Share button in the game over screen.

### Tasks

- [x] Add Platform API. Create an API for letting side projects (`desktop`, `android`...) run their own code.
- [x] Add share button. The share button is visible in game over screen.
- [x] Add desktop action. When pressed on desktop, share button will ask the user for a location in the file system for saving a screenshot to the computer.
- [x] Add Android action. When pressed on Android, share button will show a sharing intent using Android SDK for sharing the screenshot and some text to another Android app (SMS, Twitter, Facebook, WhatsApp...)

### Captures
![screenshot_2015-10-18-03-01-52](https://cloud.githubusercontent.com/assets/1568690/10561986/aa0177d2-7544-11e5-8c4c-f71ee702eb7c.png)
![filedialog](https://cloud.githubusercontent.com/assets/1568690/10559720/b4bd1f02-74f7-11e5-94f1-2fe22303f17f.png)

**Comment by danirod** [comment]
Done.
