### ISSUE TITLE
Add leaderboard support

### ISSUE THREAD

**Issue by danirod** [danirod/rectball#43]
The game has a leaderboard to display the best scores for the player. The behaviour of the leaderboard depends on the platform the game is running in. The game displays a social leaderboard if the game is running on Android, using the Google Play version and connected to Google Play Services. In any other case, it uses the fallback leaderboard.

### Tasks

- [x] Rethink the scores API.
- [x] Implement local leaderboard as a platform API.
- [x] Add support for Google Play Services.
- [x] Integrate Google Play leaderboards with Rectball.

**Comment by matiuri** [comment]
No quiero que vengan los hackers que alteren su puntuación para ser los primeros

**Comment by danirod** [comment]
Desde hace algo de tiempo Google Play tiene protección antitrampas que esconde puntuaciones que sean sospechosas y evidentemente cuando en el formulario me ha preguntado si las quiero activar he dicho sí.

De todos modos no lo considero algo 100% infalible, si alguien se esfuerza probablemente lo acabe consiguiendo. Esta gente es así. Nacieron con retraso y necesitan salir en la parte superior del marcador para demostrarlo. Esperemos que el GPE funcione.
